### ISSUE TITLE
Issue with position:sticky

### ISSUE THREAD

**Issue by axelson** [lyfeyaj/swipe#102]
Is it possible to place a `position: sticky;` element inside the swipe-wrap? I'm having issues with the `visibility: hidden` as well as the dynamically set width on the swipe-wrap container.

**Comment by axelson** [comment]
Well I don't have a working example, but here is a non-working example of the issue I am facing: https://codepen.io/anon/pen/NLMwJz

I think there are two issues relating to how swipe plays with `position: sticky`:
* Using `overflow: hidden` on any parent disables `position: sticky`
* Setting the width larger than the screen (effectively x overflow) disables `position: sticky`

There are some good examples in this thread: https://github.com/w3c/csswg-drafts/issues/865

Including a nice demo of the second issue:
https://codepen.io/valtlai/pen/XVrbPY

**Comment by loup-brun** [comment]
`position: sticky` indeed only works for scrolling containers.

You don’t actually need sticky for this. Check out [this example](https://corsaire-chaparral.org/) I made using slider navigation – just put your nav as a child of your `.swipe` element.

```html
<div class="swipe landing-slider" id="landing-slider">
  <div class="swipe-wrap">

    <!-- Your slides here go here... -->
    <div></div>
    <div></div>
    <div></div>

   </div><!-- /.swipe-wrap -->

  <!-- Slider controls, absolutely positioned -->
  <a href="#" class="slider-btn-controls slider-btn-controls-left" id="landing-slider-btn-controls-left"></a>
  <a href="#" class="slider-btn-controls slider-btn-controls-right" id="landing-slider-btn-controls-right"></a>

  <!-- Slider bullets, no need for sticky or absolute positioning -->
  <!-- The bullets are added programmatically with a little bit of js... -->
  <ul class="slider-bullets" id="landing-slider-bullets"></ul>
</div><!-- /.swipe -->
```

I'm closing this since it's not an actual issue, but feel free keep commenting or ask your questions on StackOverflow and tag `SwipeJS`! 😄
