### ISSUE TITLE
Issues with flexbox

### ISSUE THREAD

**Issue by uliverse** [lyfeyaj/swipe#111]
I am trying to use this slider in a flexbox layout. However the widths of the slides grow exponentially when resizing the viewport... Is there any fix to this problem?

**Comment by loup-brun** [comment]
could you provide a code example, like a jsbin sandbox?

**Comment by loup-brun** [comment]
you should be able to work your way around with the correct CSS.

closing as not really an issue with Swipe, but feel free to comment your example.
