### ISSUE TITLE
Event on slide is shown?

### ISSUE THREAD

**Issue by whitecolor** [lyfeyaj/swipe#13]
How about event on swipe-drag start, when new  slide is going to be shown on the sreen?

**Comment by loup-brun** [comment]
Hi @whitecolor,

If I correctly understand your concern, this feature already exists in Swipe: it's the `callback` property, passed in the `options` object when initializing Swipe.

The `callback` function is run as soon as the new slide is about to change, whereas the `transitionEnd` function is run _after_ the slide has completed the animation (hence the name). Have a look at the API in the README.

An example of usage would be:

```js
window.mySwipe = new Swipe(elem, {
  ...
  callback: myCallback // or declare it inline via an anonymous function
]);
```

Please reopen if this does not answer your request.
