### ISSUE TITLE
Each slide appears diagonally below the one before it

### ISSUE THREAD

**Issue by robbyjm** [lyfeyaj/swipe#133]
Each one of my slides is a collection of `div's` however each time I swipe the next slide appears below the last one instead of in the same place. I made a video demonstrating the problem as I thought it might be easier to understand what I am trying to fix https://streamable.com/cih6g2

**Comment by loup-brun** [comment]
Did you include the **mandatory CSS**? The styles do not appear in your demo.

**Comment by loup-brun** [comment]
Have a look at the README, [style section](https://github.com/lyfeyaj/swipe#style).

**Comment by robbyjm** [comment]
Hi @loup-brun yes I did include the mandatory css however your comment has me thinking this is a problem with the build tool I am using (parcel) and not swipe.js I will investigate and update this issue once I investigate further

**Comment by loup-brun** [comment]
When you select the swipe `div`s in your dev tools, the styles do not appear.
Your problem looks a lot like you are missing the base styles.

**Comment by robbyjm** [comment]
yeah, im going to close this because it's definitely not a bug with swipe. I just made another project and I have it working fine. Thanks for your help @loup-brun
