### ISSUE TITLE
Layout jump after init

### ISSUE THREAD

**Issue by alvarotrigo** [lyfeyaj/swipe#149]
Before initialising swipe the different "slides" of the swipe element are visible or at least taking space in the page layout.
Then, once it initialises they collapse in a single row and take the space / height they would finally take on the page.

This can be tested on the main page:
https://swipe.js.org/

By putting a breakpoint just before the initialisation:
![image](https://user-images.githubusercontent.com/1706326/102529048-ac528900-409f-11eb-9036-4383f05c7841.png)

Here you can see the huge white space:
![image](https://user-images.githubusercontent.com/1706326/102529075-b3799700-409f-11eb-9da7-13fd4a762bc5.png)

Is there any way to prevent this jump?

**Comment by lyfeyaj** [comment]
You can set `height` to swipe container and remove it after initialized

**Comment by alvarotrigo** [comment]
Yeap, that did the trick. Thanks.
