### ISSUE TITLE
mouse wheel

### ISSUE THREAD

**Issue by mPisano** [lyfeyaj/swipe#16]
Great work!

Is there anyway to add mouse wheel support for Pinch\Zoom?

also

Would love simple  <   > overlays on the sides of the images like the bootstrap carousel has

Regards,
Mike

**Comment by loup-brun** [comment]
Hi Mike,

I think some feature requests reach beyond the philosophy of Swipe, which aims to provide simple, cross-browser carousel capabilities while remaining lightweight.

Swipe provides carousel capabilities, while the UI is all left to the developer. I could send you some examples of Swipe implementations (it's essentially a CSS-related topic). You could simply copy the styles from the Bootstrap carousel and add them to your Swipe carousel.

The pinch/zoom could be an interesting feature, however you might be better off with an existing library that already does that.

Quick suggestoins:

- [PhotoSwipe](http://photoswipe.com/): a nice (though heavier) dependency-free javascript library that enables beautiful galleries with zoom, touch and cinematic looks.
- [reveal.js](http://lab.hakim.se/reveal-js/) + [zoom.js](http://lab.hakim.se/zoom-js/): [Hakim El Hattab](http://hakim.se/)'s excellent slideshow javascript library could serve as an extendable gallery. Hakim has also developed a zoom javascript library that you can combine with reveal.js, zoom.js (I've used this combination in the past :smile:). I might even be possible to integrate zoom.js with Swipe - that could be a fun experiment!
- [bigpicture.js](http://josephernest.github.io/bigpicture.js/bigpicture.html): for a Prezi-like html presentation, with scroll-zoom capabilities.

Feel free to continue the conversation below.

**Comment by mPisano** [comment]
Thanks for the response

 

Agree on the css, just thought I’d add the only other major differences between bootstrap.

 

I was really after pinch\zoom – every other platform seems to require jquery, but I think I found a solution

 

Check this out

http://manuelstofer.github.io/pinchzoom/

https://github.com/manuelstofer/pinchzoom

 

his example uses Brads original  swipe

http://manuelstofer.github.io/pinchzoom/demo/swipe.html

 

 

Going play a little code chemistry and your version with pinchzoom and see how it works!

 

Regards,

Mike

**Comment by loup-brun** [comment]
Yes, that pinchzoom integration seems pretty cool :). I'll dig into it at some point, let me know if your results are concluding. I'll close this for now, but feel free to reopen or comment further down if you can find some nice integrations, maybe we could ease them by improving Swipe or by creating a plugin.
