### ISSUE TITLE
Edge/Windows 10  Compatability

### ISSUE THREAD

**Issue by mPisano** [lyfeyaj/swipe#17]
Seem Edge touch now uses some newer pointer events that are not working with swipe.

I have noticed that if I press and hold the touchscreen that a small box does appear and if I swipe, the screen will move slighly exposing the begining of the next IMG, but snaps back.

Any Sugestions?

Thanks,
Mike

**Comment by lyfeyaj** [comment]
Hi @mPisano, can you put an example here?

**Comment by VishnuTsivan** [comment]
You have to enable touch API in edge. Enter **about:flags** in the address bar, in the section **Touch**, you can enable touch events with the corresponding dropdown

**Comment by karazon** [comment]
Although a bit late, adding
```
.swipe {
  -ms-touch-action:none;
  touch-action:none;
}
```
will fix the problem
