### ISSUE TITLE
Problems with 2 slides

### ISSUE THREAD

**Issue by Snorlock** [lyfeyaj/swipe#19]
```
      //special case if two slides
      if (browser.transitions && options.continuous && slides.length < 3) {
        element.appendChild(slides[0].cloneNode(true));
        element.appendChild(element.children[1].cloneNode(true));
        slides = element.children;
      }
```

These lines of code is creating a big problem, have anyone experienced any issues with them?
Because when im expecting to slide between 2 slides, i end up sliding between 4 and the index is Fed up. Reporting 0,1,2,3 as is reported here: https://github.com/thebird/Swipe/issues/504

**Comment by lyfeyaj** [comment]
Hi, @Snorlock 

This problem had been fixed for a long time ago. 

![image](https://cloud.githubusercontent.com/assets/1445568/13031666/33a84d84-d310-11e5-8440-a4965aeefb8c.png)

**Comment by Snorlock** [comment]
With what commit? @lyfeyaj

**Comment by lyfeyaj** [comment]
@Snorlock 
You can check below link
https://github.com/lyfeyaj/swipe/commit/91b310013e79ff59c78aa86312cdbb5fb4d5ada1#diff-12a37db95866ebcd03cc07eb41c57a9dR132

**Comment by Snorlock** [comment]
Thx :)

**Comment by sureshbuzz** [comment]
When we try to swipe still i was seeing the issue in devices..

**Comment by Geocld** [comment]
This bug is still alive!
