### ISSUE TITLE
Is there anyway to make the animation always swipe left?

### ISSUE THREAD

**Issue by losmurfs** [lyfeyaj/swipe#21]
Currently, when you get to the last slide in 2.0, when set to continuous, it swipes right to get back to the first slide.  Can we add an option so that it swipes left to go from the last slide to the first slide?

**Comment by loup-brun** [comment]
Head over to the demo page at http://lyfeyaj.github.io/swipe/ - this example should be swiping left in continuous (infinite looping) mode.

The current version is 2.0.8, maybe the version you are using is old and out of date ; make sure you are using the latest one from the repository.

Feel free to reach out if this does not solve your issue.

**Comment by loup-brun** [comment]
Closing for now - please reopen if you're still having this issue with the most recent version of Swipe.
