### ISSUE TITLE
Height of the page

### ISSUE THREAD

**Issue by VishnuTsivan** [lyfeyaj/swipe#23]
In my project, there are divs of different size. The problem is the height of the page will the height of biggest div.
Please add autoHeight feature
[swipe.zip](https://github.com/lyfeyaj/swipe/files/248431/swipe.zip)

**Comment by loup-brun** [comment]
Hi @VishnuTsivan,

This issue can be easily resolved with CSS. There are two workarounds:

* If you can predict the the height of your `div`s in advance, set them all at the same height (e.g. with `height: 300px` or `height: 100%` on elements that are `absolute`ly or `relative`ly positioned)
* If the heights of your `div`s are variable/unknown, you can center them vertically wiht the **flexible box model** (flexbox). Just add the following styles to your `.swipe-wap` element:

```css
.swipe-wrap {
  display: flex;
  flex-direction: column;
  align-items: center;
}
```

This will vertically center all your `div`s inside your slider. However, if you want ALL your slides to be the same height (i.e., the height of the `.swipe-wrap` container), flexbox has you covered too! Just change the last line to `align-items: stretch` and all your `div`s will be the same height!

I'll close this as it is not directly related to `swipe` functionality. Feel free to reopen if you think this feature must be incorporated into `swipe` and cannot as such be resolved with CSS!
