### ISSUE TITLE
offloadFn not used as intended

### ISSUE THREAD

**Issue by henrikland** [lyfeyaj/swipe#24]
`offloadFn` is presumably used to delay execution of a function until the next execution cycle:
`var offloadFn = function(fn) { setTimeout(fn || noop, 0); }; // offload a functions execution`

However, everywhere in the code where it is used, the argument function is called instead of sent as a reference:
`offloadFn(options.callback && options.callback(getPos(), slides[index]));`
`case 'touchend': offloadFn(this.end(event)); break;`

So these functions are not offloaded, and since they all lack return statements they evaluate to undefined and `noop` gets called from `offloadFn`.

This doesn't seem to have an impact on anything yet, but I thought you should be made aware. Let me know if I should submit a pull request with a fix!

**Comment by lyfeyaj** [comment]
@henrikland Thanks for pointing it out. Pull request is welcome! 😄

**Comment by lyfeyaj** [comment]
fixed
