### ISSUE TITLE
"to" has wrong type

### ISSUE THREAD

**Issue by seebaermichi** [lyfeyaj/swipe#25]
The type of variable `to` in method `slide()` is of `string`. This results in wrong behavior if first slide is active and method `slide()` is called with last index (only if continuous is enabled).
In addition slider breaks whole page if `slide()` is called with current slide. 

See pen: http://codepen.io/MichaB/full/PNMJYb/

The reason for this is, that `to` is of type `string` and not `number`.

**Comment by lyfeyaj** [comment]
#27
