### ISSUE TITLE
can't make it work... :(

### ISSUE THREAD

**Issue by andreaconsole** [lyfeyaj/swipe#32]
I downloaded the zip file on my test web server, unzipped it and tried it locally. The page I see in my browser contains the introductory text but no slides (I see slides 0 and 1 that vanish after 3 seconds and the page is very long). What am I doing wrong?
I use chrome on linux 16.04 and apache 2 web server. It's not the browser because this snippet works perfectly https://codepen.io/justincavery/pen/saEyI/ . Nevertheless I can not make it work on my server.

**Comment by loup-brun** [comment]
Does the console output anything? Can you make a link to your server? Did you alter any of the code/CSS?

**Comment by andreaconsole** [comment]
Thank you for answering.
No errors communicated by the console (chrome tools for developers). The code is the original one (if I open index.html via the browser it works, if I go to 127.0.0.1 it doesn't). The server is local, no external access. It's a default installation of Apache2+php

**Comment by loup-brun** [comment]
Hum, no idea. It's not related to the code, that's for sure. It's not normal behavior. Could you try everything again from scratch? I cloned the repo in a fresh directory on my Apache server and it worked (whether I omitted the trailing `index.html` or not).

**Comment by andreaconsole** [comment]
Thank you, a new installation of everything worked, although I still can't understand what happened. Sorry for having bothered you

**Comment by loup-brun** [comment]
Great, have fun!
