### ISSUE TITLE
how to fix the scroll between swipe and origin scroll

### ISSUE THREAD

**Issue by yuzai** [lyfeyaj/swipe#34]
I use swipe like below:
```
<div id="slider" class="swipe">
  <div class="swipe-wrap">
    <div><div id='ex'></div></div>
    <div></div>
    <div></div>
  </div>
</div>
```
in style sheet.I set a 'overflow:auto' for ‘ex‘ and 'ex' width is larger than swipe.
here is the question:
it didn't work in swipe, seems like the overflow:auto 's scroll is conflict with scroll in swipe?
Is there any way to fix this in swipe or I just put this element outside?.I need this element to scroll and in different slide ,its' content is not same

**Comment by loup-brun** [comment]
Hi @yuzai 
If your `div[id="ex"]` is wider than the slide, you should set its **parent** `div` to `overflow: auto`. That way, the width of the slide will remain preserved (and Swipe will work), and scrollbars will appear.

However, you will probably still run into some issues with click/touch events, since horizontal drags will not trigger the scrollbars (Swipe will catch them and move the slider).

```html
<div id="slider" class="swipe">
  <div class="swipe-wrap">
    <div class="overflow-auto"><div id="ex"></div></div>
    <div></div>
    <div></div>
  </div>
</div>
```

Here's a quick example I did in the browser with an `overflow: auto`. It works, but as I said, dragging the scrollbar horizontally actually moves the slide, not the scrollbar.
![2016-10-13_100845](https://cloud.githubusercontent.com/assets/9596476/19352290/55b9aa7c-912d-11e6-9179-1acf09094eaa.jpg)

Hope that helps 😃

**Comment by yuzai** [comment]
Thank you anyway.
I know it's father element. My problem is like this.
this is before use swipe:
![image](https://cloud.githubusercontent.com/assets/16518346/19390162/757340b2-9259-11e6-86f4-61865658ece5.png)
here is code:
```
<div style = 'overflow:auto'><div style = 'height:200px;width:2000px;background-color:red;'></div></div>
    <div style = 'overflow:auto'><div style = 'height:200px;width:2000px;background-color:yellow;'></div></div>
    <div style = 'overflow:auto'><div style = 'height:200px;width:2000px;background-color:grey;'></div></div>
```


with swipe around it:
```
<div id="slider" class="swipe">
  <div class="swipe-wrap">
    <div style = 'overflow:auto'><div style = 'height:200px;width:2000px;background-color:red;'></div></div>
    <div style = 'overflow:auto'><div style = 'height:200px;width:2000px;background-color:yellow;'></div></div>
    <div style = 'overflow:auto'><div style = 'height:200px;width:2000px;background-color:grey;'></div></div>
  </div>
</div>
```
in mobile ,the scrollbar disappear, and I can't drag the div to scroll it  any more. when I drag, it will slide.
Anyway ,thank you.

**Comment by loup-brun** [comment]
I'm not sure why you would like to use scrollbars in a carousel, which itself contains swipable content.

I'll close this for now, since it isn't actually a bug with the software, but a special design case.

**Comment by loup-brun** [comment]
Finally, if you want something like nested carousels, check out [Swiper](http://idangero.us/swiper/), which is pretty neat, but  which features go beyond the goals of Swipe.

**Comment by yuzai** [comment]
you are right. it's not a bug, just a special design case. Thank you anyway

**Comment by yuzai** [comment]
one more thing, I just wonder can we just add a new function to these special case?
like if I add an element in swipe a class such as "can scroll", then when we scroll that area, the element can scroll while swipe doesn't.

**Comment by loup-brun** [comment]
But if the swipe functionality is disabled, the carousel no longer works (i.e., the user can no longer swipe between slides)!

Could you send me a concrete example of what you are trying to achieve?

**Comment by yuzai** [comment]
I am building a weather-app, it's not a big project.
it looks like this:
![image](https://cloud.githubusercontent.com/assets/16518346/19461296/186f328a-9516-11e6-8a74-6126a6a2871b.png)
in my first version, **this area** 
![image](https://cloud.githubusercontent.com/assets/16518346/19461314/4268c2cc-9516-11e6-9924-14ba0e0bfb8a.png)
**is wider than screen width.** (in fact I want to show more weather forecast and I don't want this to be so dense)
At the right up corner in first picture, there is an add_city button, I can add city using that button. this is why I use swipe, I want to swipe between cities. **But when I screen that area in picture 2, I hope I can screen this area to see more information. while when I screen other area, I can swipe between cities.**

**Comment by yuzai** [comment]
Hi, I solved this problem, but this is not necessary.
I want **the area** can scroll to show more information and won't catched by swipe.
So I add this element an EventListener like below:
`lineweather.addEventListener('touchstart',stop,false);
function stop(event){
  event.stopPropagation();
}`
so the 'touchstart' won't  Propagation to 'swipe'.
It's easy but before, i am really fool to javascript.
Thanks for your reply before!
This change is not necessary to this project, so I close it.
thanks again.
