### ISSUE TITLE
.kill() not executing properly on window resize [bug]

### ISSUE THREAD

**Issue by AlexanderYW** [lyfeyaj/swipe#35]
when using .kill() eg if i'm going from mobile view with swipe to desktop it dosent clean up all the inline styling
```
$(window).on('resize', function() {
    if($(window).width() < 800) {
        window.mySwipe = new Swipe(document.getElementById('slider'));
    } else {
        window.mySwipe.kill()
    }
});
```

Also if i only have to slides it doesn't clean up properly because of the "special case senario" on line 80 in swipe.js, there is no "special case senario" in the .kill() for that

**Comment by loup-brun** [comment]
Could you be more specific about the inline styling you find should be removed?

Regarding your piece of code, you should call the `setup` function rather than instantiating `Swipe` on every resize event.

```js
$(window).on('resize', function() {
  if($(window).width() < 800) {
    window.mySwipe.setup();
  } else {
    window.mySwipe.kill()
  }
});
```

I am creating a fix to remove the cloned slides on `kill` (special case for 2 slides).

**Comment by loup-brun** [comment]
There is an issue when only using the `setup` method: some events are not registered inside that function. Will look into it during the fix.

**Comment by AlexanderYW** [comment]
Its the inline styling on the swipe views/"pages" (.swipe -> .swipe-warp -> div <- this)

Regarding the .setup() your right, i forgot about that one, thanks!

When are your fix going live?, not sure if the NPM is updating from Github or you have to tell it to, because I'm using the one from there :)

**Comment by AlexanderYW** [comment]
About the issue with .setup(), same goes for when you are using swipe through jquery "$('#swipe').Swipe()", callback does not trigger i think it was

**Comment by loup-brun** [comment]
The issue should now be fixed, see the latest release ([2.0.12](https://github.com/lyfeyaj/swipe/releases/tag/2.0.12)).

Summary:

* Inline styles applied by Swipe (transition, transition-duration, etc.) are now removed.
* Event handlers are bound during the `setup` (and not only when calling a new Swipe instance).
* Cloned slides for 2-slide scenario are tagged and removed on `kill` to avoid confusion with original ones.

Let me know if you still have some issues!

**Comment by loup-brun** [comment]
As for the other repositories, such as NPM and Bower… I guess @lyfeyaj has to push the changes there?

**Comment by lyfeyaj** [comment]
@loup-brun @AlexanderYW 

Version 2.0.12 has been pushed to npm registry.
Bower will be updated automatically after bower.json changed.

**Comment by loup-brun** [comment]
Great! So the only thing left is feedback from @AlexanderYW to make sure the issue has been resolved.

**Comment by AlexanderYW** [comment]
Awesome job guys, it works like a charm now!

I'm closing this one, since the problem is solved
