### ISSUE TITLE
React support

### ISSUE THREAD

**Issue by pcegarra** [lyfeyaj/swipe#36]
Would be great has this as component from react!

**Comment by lyfeyaj** [comment]
Yes, I was just planning about adding react support

**Comment by lyfeyaj** [comment]
@pcegarra Please help to check whether #38 can meet your needs

**Comment by lyfeyaj** [comment]
Hi, @pcegarra 
Swipe with react support has been released(v2.1.0), please install the latest version: `npm install swipejs@latest`

**Comment by pcegarra** [comment]
Its working like a charm, but..
How can I call the button next and prev?
