### ISSUE TITLE
long time tap trigger 

### ISSUE THREAD

**Issue by vicvinc** [lyfeyaj/swipe#37]
sorry this only happened in some android device... 
@before update
``with long time taped on the carousel, the swipe time may change to smaller than options.auto, and some times the sequence may not be right.
tested on mobile browser. on tap without touch move.``

**Comment by lyfeyaj** [comment]
@vicvinc Can you provide those android devices' model that may have above issue?

**Comment by vicvinc** [comment]
thanks for reply, founded in earlier version of UC browser and android 4.4, some options in the browser like long tab to view images in full screen view caused this.  individual problems, sorry for not find out the radical reason.
