### ISSUE TITLE
Dont allow swipe back

### ISSUE THREAD

**Issue by pcegarra** [lyfeyaj/swipe#40]
Can we disable the swipe back?

**Comment by lyfeyaj** [comment]
Not quite clear about your question.... can you be more specific?

**Comment by pcegarra** [comment]
Im interested only in a swipe component with slide forward. Then I need to block the swipe back.

I want users cant go backwards on the slide.

**Comment by lyfeyaj** [comment]
This feature is not supported by swipe itself for now. Any idea of how to implement it? @pcegarra

**Comment by loup-brun** [comment]
If pull request #44 is good to ship, you could use the API to find the direction and prevent swipe in a given direction. All you would have to do is add something like below to your `callback` function when initializing Swipe:

```js
// Swipe init
// ...
  callback: function(index, element, dir) {
    if (dir > 0) { // i.e. if we're moving left, backward
      mySwipe.slide(index -1)
    }
  }
// ...
```

**Comment by loup-brun** [comment]
@pcegarra As of 2.2.1 the **direction** feature has been implemented. You can thus accomplish preventing swipe back using the above snippet. Let me know if this works for you!

**Comment by lyfeyaj** [comment]
Version 2.2.0 has been released.
