### ISSUE TITLE
Calling setup onResize is unnecessary

### ISSUE THREAD

**Issue by sebworks** [lyfeyaj/swipe#42]
The code is currently calling the `setup` method when the window resizes. The result is unnecessary processing and the addition of duplicative event handlers. Should probably just have a method which updates the positions and dimensions of the necessary elements.
```
 case 'resize': offloadFn(updateDimensions); break;

    function updateDimensions() {
      // determine width of each slide
      width = container.getBoundingClientRect().width || container.offsetWidth;

      element.style.width = (slides.length * width * 2) + 'px';

      // stack elements
      var pos = slides.length;
      while(pos--) {

        var slide = slides[pos];

        slide.style.width = width + 'px';
        slide.setAttribute('data-index', pos);

        if (browser.transitions) {
          slide.style.left = (pos * -width) + 'px';
          move(pos, index > pos ? -width : (index < pos ? width : 0), 0);
        }

      }
    }
```

**Comment by lyfeyaj** [comment]
In case for some custom DOM change during resize, those setup operations are still needed to be executed to make sure the slide perform well. 

`swipejs@2.1.3` is released: fix duplicative event handlers when calling setup

**Comment by sebworks** [comment]
@lyfeyaj, should the code be throttling onResize as mentioned here: https://developer.mozilla.org/en-US/docs/Web/Events/resize

**Comment by sebworks** [comment]
I guess I'm struggling to see how this can possibly be performant. You are essentially detaching / reattaching event handlers every time a user resizes the browser ( potentially 100s of times ) . Why detach and then reattach? Seems unnecessary.

**Comment by lyfeyaj** [comment]
@sebworks  Yes, we can use throttle to optimize the code, will add it later

**Comment by lyfeyaj** [comment]
`throttled setup` added in `swipejs@2.1.4`
