### ISSUE TITLE
Events not being attached when bundling with Webpack

### ISSUE THREAD

**Issue by kintesh** [lyfeyaj/swipe#45]
The variable `root` is empty object when checking browser capabilities.Therefore `browser.addEventListener` will always be false and will not add any events.

**Comment by lyfeyaj** [comment]
@kintesh Please help to see whether #47 can fix your problem

**Comment by lyfeyaj** [comment]
I've test it through `example/react` and it's working.

**Comment by kintesh** [comment]
It works me for too. Thanks.

**Comment by lyfeyaj** [comment]
Great, version `2.1.5` has been released with this issue fixed.
