### ISSUE TITLE
kill() should remove any throttled function timeouts

### ISSUE THREAD

**Issue by nathanielw** [lyfeyaj/swipe#48]
Currently if you call `kill()` on resize (e.g. to show the slider only at smaller sizes), the slider will be destroyed momentarily, before popping back into the page. This seems to be because `kill()` doesn't remove the throttled `setup` call from the window, so `setup` ends up getting called ~100ms after resizing/killing the slider.

**Comment by lyfeyaj** [comment]
Fixed by #49, please use the latest version: `swipejs@2.2.1`
