### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by basharov** [lyfeyaj/swipe#50]
First, thanks for the great compact jQuery-less swipe library!

Can you please advise me if there is any d.ts file for this library or is there a chance you could include it into the repo or make it possible to fetch it from some identified source?

**Comment by lyfeyaj** [comment]
It will be great for adding support for typescript, but I am not sure how to do it. 
Could you give some instructions?  Or, a corresponding pull request is welcome 🙏

**Comment by basharov** [comment]
I have found an existing types package, so you can mention it in Readme - https://www.npmjs.com/package/@types/swipe

**Comment by lyfeyaj** [comment]
The `@types/swipe` you mentioned is for the old and dead `swipe` project and is not fully compatible with current version of this project

**Comment by basharov** [comment]
Agree, though, it can be a temporary workaround.

**Comment by lyfeyaj** [comment]
@basharov Version 2.2.3 has been released with typescript support. You can check #54 for details.
