### ISSUE TITLE
Feature request: Add a callback for a move

### ISSUE THREAD

**Issue by basharov** [lyfeyaj/swipe#53]
I have an indicator that should change its position depending on the current position of the slide that is being moved with the touch. When I start moving a slide, I want to change the indicator position and size depending on the current position of the slide that is being dragged.

So, It would be great to have a way to attach a callback to every 'move' event with some data inside, like coordinates, shift and other.

Thanks!

**Comment by lyfeyaj** [comment]
![image](https://cloud.githubusercontent.com/assets/1445568/20597389/4d1e1c8c-b27e-11e6-9f09-be23801d8d4b.png)

As described above. There are two kinds of function callback accepted: `callback` and `transitionEnd`.

`callback` runs at slide change and `transitionEnd` runs at the end of a slide transition.

**Comment by basharov** [comment]
`callback` runs only when the slide changes. What I mean is a callback for each move on x or y, like this http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onmousemove.

**Comment by loup-brun** [comment]
This is possible. What would you like to see in the API precisely? Absolute mouse/touch coordinates? Distance traveled? Bear in mind though that attaching an extra callback on _every move_ can be costly.
