### ISSUE TITLE
Add RTL Support

### ISSUE THREAD

**Issue by krulik** [lyfeyaj/swipe#58]
Hey, great work in the original project making this small and useful tool, exactly what I need!
Also great job maintaining and keeping this alive, thanks!

I'm working on an RTL website and after setting up Swipe I can't see anything.
Changing to `<html dir="ltr">` make it work.
Also adding `dir="ltr"` to the Swipe container.
First is of course impossible, and the second is sub-optimal since the direction of sliding is the opposite.

I went over the code to see if it's an easy fix but it seems a couple of hours work (at least for me) to get all the calculations right.
Is there a plan to add a setting for direction?

**Comment by lyfeyaj** [comment]
I am not quite familiar with RTL websites. From some preliminary research, TRL seems to be not that easy to implement and probably won't be added in the immediate future.

However, pull request of this feature is extremely welcome 😄.  We can work to together to make it work if you are interested.

**Comment by krulik** [comment]
Sure, let's do this together.

Moving from LTR to RTL boils down to changing all direction sensitive calculations/styles. For example if we have a `margin-left` we should change it to `margin-right` (or create a dynamic option). Or if an animation's doing `+` to move an element it should instead `-`.

A first step would be identifying all the places in the code where such calculations/styles are made.

**Comment by byzyk** [comment]
Hey, guys!
Faced with the same issue today. Let me know if someone has already started on the PR and you need any help. 
Otherwise, I'll try to get it done over the weekend.

**Comment by krulik** [comment]
@byzyk unfortunately not, eventually I went with the sub optimal solution of sliding opposite direction and had no time to improve it since.
