### ISSUE TITLE
Wrong initial item width

### ISSUE THREAD

**Issue by TornjV** [lyfeyaj/swipe#60]
The problem seems to be identical to [this](https://github.com/voronianski/react-swipe/issues/98) one.

I'm using the react component. Trying to run swipe.instance.setup() in componentDidMount does not work since it's undefined, only when the page completely renders is when setup() can be called and does what it's supposed to do. The width seems to be correct on mobile though.

**Comment by monteiz** [comment]
hi @TornjV,
I worked around that by doing the following:

```
	componentDidMount() {
		this.mySwipe = this.refs.swipe.instance;
	}

	componentDidUpdate() {
		this.mySwipe.setup();
	}
```
