### ISSUE TITLE
Which style.css file need to be hosted?

### ISSUE THREAD

**Issue by sufuf3** [lyfeyaj/swipe#63]
Hi @lyfeyaj , 
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We are going to host this library.

There are not only one `style.css` in the different path(root or under `dist`), which one is correct?

If you have any suggestions, please let me know.

Thank you.

cdnjs/cdnjs#10448

**Comment by lyfeyaj** [comment]
Thanks for hosting this library. The ***[root](https://github.com/lyfeyaj/swipe/blob/master/style.css)*** one is correct.

**Comment by sufuf3** [comment]
Thanks @lyfeyaj
