### ISSUE TITLE
main.js:51062 Uncaught TypeError: Cannot set property 'Swipe' of undefined

### ISSUE THREAD

**Issue by laengyog** [lyfeyaj/swipe#67]
in react : 
![image](https://cloud.githubusercontent.com/assets/7719602/25211737/514a6b36-25b9-11e7-9c8e-27d926c6d5ce.png)

**Comment by liyatang** [comment]
+1 ， webpack translate this to undefined(line 29)

**Comment by lyfeyaj** [comment]
@laengyog @liyatang which version of webpack do you use?

**Comment by owcc** [comment]
same error with react! v2.2.6

**Comment by owcc** [comment]
same problem! webpack@1.13.1

**Comment by dashkevych** [comment]
I am getting the same issue when using **babel** with '@babel/preset-env' in gulp.

`
Uncaught TypeError: Cannot set property 'Swipe' of undefined
    at swipe.js:50
    at swipe.js:52
`

![JS issue](https://snipboard.io/qJrEZ6.jpg)

**Comment by postbird** [comment]
same issue with weback@4.42.0

**Comment by postbird** [comment]
Duplicate of #135

**Comment by lyfeyaj** [comment]
Fixed in #136
