### ISSUE TITLE
Feature request - Disable drag next/prev

### ISSUE THREAD

**Issue by maxfahl** [lyfeyaj/swipe#74]
I don't know if this is something you want to implements. But I have a use case where I would like to disable the user from dragging in the next or previous slide depending on the state in my application.

I have a slider that contains a start section with controls for joining a Quiz, the last section is to show the results of the Quiz. Between these sections are slides that represents each question. I would like to let the competitors of the quiz be able to drag the slider (on a mobile browser) between questions, but not to the first/last section. The swap to first/last section of the slider will be made through the code by triggering these states in a control panel kind of thing by another user in another app.

I hope to have explained my use case, but maybe this is a bit to advanced of a feature to be implemented in this elegant slider.

**Comment by lyfeyaj** [comment]
@maxfahl Try version `swipejs@2.2.8`. two methods have been added to swipe instance: `mySwipe.disable()` and `mySwipe.enable()`. Hope this can meet you requirement. 😃

**Comment by maxfahl** [comment]
Hey man, thanks for your answer.

I'm not looking to disable/enable the entire swipe instance. I need to be able to disable slide prev/next depending on certain criteria.

Say I have slides 1, 2, 3, 4 & 5. At this points I would like to prevent the user from sliding to slide 1 & 5 when they're at the slides between (2, 3 & 4). If the user slides from 1 to 2, he won't be able to slide back to the first slide.

Do you see what I mean? :)

**Comment by lyfeyaj** [comment]
That's a little complicated. Any idea on how to implement this feature?

**Comment by Novalis80** [comment]
some function will check every time before a swipe is done if it is allowed to swipe. e.g: mySwipe,swipeabled(someUserFunction)

`mySwipe.swipeabled(function(slideNow, slideToGo, allSlides){
        // user does whatever
     return true; // will swipe to "slideToGo"
     return false; // will not allow the swipe to happen
});`

**Comment by maxfahl** [comment]
I ended up writing a custom swiper for my project. Thanks for your responses anyway.
