### ISSUE TITLE
React "Swipe" Component doesn't unmount because of a typo

### ISSUE THREAD

**Issue by le0nik** [lyfeyaj/swipe#84]
`componentWillUmount` should be `componentWillUnmount` here

https://github.com/lyfeyaj/swipe/blob/master/react/swipe.jsx#L86

Will submit PR asap.

**Comment by le0nik** [comment]
PR: https://github.com/lyfeyaj/swipe/pull/85

**Comment by lyfeyaj** [comment]
Try version `swipejs@2.2.10`

**Comment by le0nik** [comment]
Fixed in `2.2.10`.

P.S.: Just for those who saw an error `Unexpected call to method or property access` in IE 11. It was caused by this issue. Update to `>=2.2.10` to fix it.
