### ISSUE TITLE
Swiping doesn't work with images

### ISSUE THREAD

**Issue by novito** [lyfeyaj/swipe#88]
Hello, thanks a lot for working on this library. I've found what seems to be a bug. Happy to work on a PR if you can provide some hints.

# Problem

When trying to swipe images (on a desktop), I am not able to do so. It's dragging the image, and even after adding `draggable=false`, I can't do it. Example: http://jsfiddle.net/85rr53fm/22/ . However, I can do that in the example provided in the README.

# Expected behavior

Images are also swippable

**Comment by lyfeyaj** [comment]
Hi, the external resource you used is `https://cdnjs.cloudflare.com/ajax/libs/swipe/2.0/swipe.min.js`, which was the old swipe repo.

You should try the latest version `swipejs@2.2.10`.

Try <https://jsfiddle.net/85rr53fm/23/> to see whether your problem can be resolved.

**Comment by novito** [comment]
@lyfeyaj I still can't swipe the images in https://jsfiddle.net/85rr53fm/23/ when visiting from my desktop + chrome. It's using the dragging functionality.

**Comment by novito** [comment]
sigh, I had the `draggable` option in `false`. Sorry

**Comment by novito** [comment]
@lyfeyaj actually I have a question here. Is there any way to allow both the desktop draggable and the mobile draggable to work side by side? I want for both desktop users using a small screen as well as mobile users to be able to swipe.
