### ISSUE TITLE
Does this support group cells?

### ISSUE THREAD

**Issue by nilsi** [lyfeyaj/swipe#92]
Hi, Is it possible to show two slidable divs at the same time with this swipejs? Im looking for something like flickity's groupCells: 2

https://flickity.metafizzy.co/options.html#groupcells

I want to show two cells on desktop and one on mobile. Thanks for the help.

**Comment by lyfeyaj** [comment]
Not support yet

**Comment by warapitiya** [comment]
Any plans for this?

**Comment by lyfeyaj** [comment]
No plan for this feature in the long run.
