### ISSUE TITLE
Swipe inside transformed element

### ISSUE THREAD

**Issue by julifos** [lyfeyaj/swipe#95]
I have a swipe component living inside a DIV which changes its size from time to time using a regular css transform. The calculations of each slide width are "wrong", see line 493 @ swipe.js:

`width = container.getBoundingClientRect().width || container.offsetWidth;`

Apparently `offsetWidth` returns the width of the element as originally set before transformations, while `getBoundingClientRect()` takes the transformation into consideration, so I don't quite understand this OR, as it returns very different things. Why `getBoundingClientRect()` is preferred against `offsetWidth`?

As it's working now in my environment, I have slides much wider or narrow than they should, depending on the transform being applied.

Cheers!

**Comment by lyfeyaj** [comment]
`offsetWidth` will round the value to an integer. `element.getBoundingClientRect()` will return more fractional value.
