### ISSUE TITLE
Firing an event on swipe initialised

### ISSUE THREAD

**Issue by eighthday** [lyfeyaj/swipe#99]
Is is possible to check when swipe has initialised on load? e.g an onInit callback? I need to return the first slide on load.

**Comment by loup-brun** [comment]
Since javascript follows a linear thread, you should be able to access you Swipe instance right after you instanciate it:

```js
// create your Swipe instance
var mySwipe = new Swipe(elem, {/* options */});

// mySwipe is now instanciated and available to call
console.log(mySwipe); // should return your Swipe instance
```

Alternatively, abstract your Swipe init in a function:

```js
function initMySwipe() {
  window.mySwipe = new Swipe(elem, {/* options */});
  
  /* do something as your Swipe inits */
  
  return window.mySwipe; // return a reference to your Swipe instance
}

// Initialize your Swipe instance
initMySwipe();
```

**Comment by eighthday** [comment]
thanks for the quick reply - how can I get the elem ?

**Comment by loup-brun** [comment]
From the [source](https://github.com/lyfeyaj/swipe/blob/master/swipe.js#L468) – you can actually get the first slide without Swipe. Just call `element.children` where `element` is your `.swipe-wrap` container.

```js
// get the first slide, assuming `element` is your `.swipe-wrap` DOM element
var firstSlide = element.children[0];
```
